### PR TITLE
remove gemspec and attr_readers for devices

### PR DESCRIPTION
**Pull request by RyanScottLewis**

### CODE REVIEW

**Comment by RyanScottLewis** [comment]
Bah ignore `examples/input.rb` if you pull this. My bad.

**Comment by arirusso** [comment]
Ah, figured...nbd

I already removed the gemspec a couple of days ago...can't hurt

I can merge in the comments but I generally prefer attr_reader since it is more explicit. Maybe you know something about attr_reader that I don't?  I'm all ears if so...

**Comment by RyanScottLewis** [comment]
Nope, just needed a better way to access these variables

**Comment by RyanScottLewis** [comment]
This last commit enables my BCR2000 to run =)

**Comment by arirusso** [comment]
what are you trying to accomplish with accessing those vars? there may be another way...

the last commit is great, thanks. lemme just figure out how to merge it...

**Comment by RyanScottLewis** [comment]
`my_device = MIDIWinMM::Input.all.find { |d| d.name == "BCR2000" }`

instead of

`my_device = MIDIWinMM::Input.all.find { |d| d.instance_eval { @name } == "BCR2000" }`

**Comment by arirusso** [comment]
right on

**Comment by RyanScottLewis** [comment]
eventually could be replaced by

`MIDIWinMM::Input.find_by_name(/Yoke/)`

My testing branch has that functionality.

**Comment by arirusso** [comment]
I would be more inclined to add that kind of stuff to unimidi and keep these platform libs as simple and low-level as possible

**Comment by RyanScottLewis** [comment]
Ah yes, of coarse. Didn't even notice unimidi until now. =)

**Comment by arirusso** [comment]
whoops, it's been a long day...  

I have the messaging library that I mentioned before on it's way in the next few days...

**Comment by arirusso** [comment]
please clone the latest version and test it with your bcr2000 when you get a chance. once we know it works i'll push a new gem

**Comment by RyanScottLewis** [comment]
works great

**Comment by arirusso** [comment]
alright, thanks! the gem is pushed

**Pull request closed without merging**
